apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: blue-green # Updating our existing route
  namespace: default
spec:
  traffic:
  - revisionName: blue-green-00001
    percent: 50 # Updating the percentage from 100 to 50
  - revisionName: blue-green-00002
    percent: 50 # Updating the percentage from 0 to 50
    name: v2